BAU: fix boolean logic
communitiesuk/funding-service-design-application-store pull request #94
Opened 2022-11-18 12:15 UTC by gidsg

Previously this was unintentionally always evaluating to True as `"gwybodaeth-am-y-prosiect"` was always truthy due to missing brackets.

2022-11-18 12:31 UTC, tferns approved these changes
Looks good 👍

2022-11-18 12:33 UTC, tferns reviewed
Actually, dismiss my review before.

Shouldn't this be:

```
if form_name in ("project-information" or "gwybodaeth-am-y-prosiect"):
```

2022-11-18 13:14 UTC, Adam-W1 commented
> 
yep agreed @tferns, my bad. twas a suggestion on the fly :=[

2022-11-18 13:15 UTC, Adam-W1 requested changes

2022-11-18 13:15 UTC, Adam-W1 commented on db/models/aggregate_functions.py
> +    if form_name == ("project-information" or "gwybodaeth-am-y-prosiect"):
```suggestion
    if form_name in ("project-information", "gwybodaeth-am-y-prosiect"):
```

2022-11-21 09:59 UTC, Adam-W1 approved these changes

2022-11-21 10:01 UTC, merged